name: Deploy

on:
  # Triggers the workflow on push to master branch
  push:
    branches: [ master ]
  # Allows to trigger workflow manually
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: [ubuntu-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Nodejs
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Cache dependencies
      id: cache-node-modules
      uses: actions/cache@v3
      env:
        CACHE_NAME: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-cache-
          ${{ runner.os }}-

    - name: Install dependencies
      if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
      run: npm ci

    - name: Build
      run: npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
